version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wheelsonrent
      POSTGRES_PASSWORD: wheelsonrentpass
      POSTGRES_DB: wheelsonrentdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./wheelsonrent
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wheelsonrentdb
      SPRING_DATASOURCE_USERNAME: wheelsonrent
      SPRING_DATASOURCE_PASSWORD: wheelsonrentpass
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./wheels-on-rent-frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
